Repository woowacourse-study/2023-gb-code, pull requests merged in 2023-04, with the labels that each got.

#20 [SQL 첫걸음] 1강, 2강 정리
  somsom13/SQL_첫걸음/1장_데이터베이스와_SQL/01_데이터베이스.md
  somsom13/SQL_첫걸음/1장_데이터베이스와_SQL/02_다양한_데이터베이스.md
  somsom13/좋은코드_나쁜코드/1장/코드_품질.md
  somsom13/좋은코드_나쁜코드/2장/추상화_계층.md
Labels: 바론

#18 [SQL 첫걸음] 1강, 2강 정리
  yeonkkk/SQL_첫걸음/1장/01_데이터베이스.md
  yeonkkk/SQL_첫걸음/1장/02_다양한_데이터베이스.md
Labels: 조이

#26 [SQL 첫걸음] 3~8강 정리
  yeonkkk/SQL_첫걸음/1장/03_데이터베이스_서버.md
  yeonkkk/SQL_첫걸음/2장/04_Hello_World_실행하기.md
  yeonkkk/SQL_첫걸음/2장/05_테이블_구조_참조하기.md
  yeonkkk/SQL_첫걸음/2장/06_검색_조건_지정하기.md
  yeonkkk/SQL_첫걸음/2장/07_조건_조합하기.md
  yeonkkk/SQL_첫걸음/2장/08_패턴_매칭에_의한_검색.md
Labels: 조이

#28 [SQL 첫걸음] 4강 ~ 10강 정리
  jj503/SQL 첫걸음/2장 테이블에서 데이터 검색/4강 Hello World 실행하기.md
  jj503/SQL 첫걸음/2장 테이블에서 데이터 검색/5강 테이블 구조 참조하기.md
  jj503/SQL 첫걸음/2장 테이블에서 데이터 검색/6강 검색 조건 지정하기.md
  jj503/SQL 첫걸음/2장 테이블에서 데이터 검색/7강 조건 조합하기.md
  jj503/SQL 첫걸음/2장 테이블에서 데이터 검색/8강 패턴 매칭에 의한 검색.md
  jj503/SQL 첫걸음/3장 정렬과 연산/10강 복수의 열을 지정해 정렬하기.md
  jj503/SQL 첫걸음/3장 정렬과 연산/11강 결과 행 제한하기 - LIMIT.md
  jj503/SQL 첫걸음/3장 정렬과 연산/9강 정렬 - ORDER BY.md
Labels: 제이미

#27 [SQL 첫걸음] 3강 ~ 8강 정리
  somsom13/SQL_첫걸음/1장_데이터베이스와_SQL/03_데이터베이스_서버.md
  somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/04_Hello_World_실행하기.md
  somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/05_테이블_구조_참조하기.md
  somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/06_검색_조건_지정하기.md
  somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/07_조건_조합하기.md
  somsom13/SQL_첫걸음/2장_테이블에서_데이터_검색/08_패턴_매칭에_의한_검색.md
Labels: 바론
